name: livedisciplined
favicon: null
layout_spectrum: 0.10486593306995928
typography_spectrum: 0.17892544879578054
title: livedisciplined
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5177357229404151
  lightness: 0.54320348193869
  saturation: 0.9946871399879456
  rhythmicContrast: 0.841933272080496
purpose: []
